package card.views;
/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import java.util.Date;

import framework.models.IAccount;
import framework.models.ICustomer;
import framework.views.FincoFrm;

public class JDialogGenBill extends javax.swing.JDialog {

	String reportString;
	// {{DECLARE_CONTROLS
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JTextArea JTextField1 = new javax.swing.JTextArea();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();

	public JDialogGenBill(Frame parent) {
		super(parent);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parses your Java file into its visual envirenment.
		// {{ INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(405, 367);
		setVisible(false);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24, 24, 358, 240);
		JScrollPane1.getViewport().add(JTextField1);
		JTextField1.setBounds(0, 0, 355, 237);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(156, 276, 96, 24);

		for (ICustomer customer : CardFrm.customersList) {
			reportString = "Name = " + customer.getName() + "\n";
			reportString += "Address = " + customer.getStreet() + "," + customer.getCity() + "," + customer.getState()
					+ "," + customer.getZip() + "\n";
			for (IAccount account : customer.getAccountList())
				reportString += account.report(new Date());			
		}

		JTextField1.setText(reportString);
		// }}

		// {{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		// }}
	}

	public JDialogGenBill() {
		this((Frame) null);
	}
	// }}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {
		dispose();

	}

	class SymAction implements java.awt.event.ActionListener {
		public void actionPerformed(java.awt.event.ActionEvent event) {
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
		}
	}
}
